AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.3.1

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"
