storage:
  image: busybox
  volumes:
      - /var/lib/postgresql/data
db:
  image: postgres:9.6.1
  environment:
    POSTGRES_USER: tenarai
    POSTGRES_PASSWORD: tenarai
  ports:
    - "5432:5432"
  volumes_from:
      - storage
redis:
  image: redis:3.2.6
  ports:
    - "6379:6379"

elasticsearch:
  image: nasum/elasticsearch-kuromoji:0.0.2
  ports:
    - "9200:9200"
    - "9300:9300"
