default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tenarai
  password: <%= ENV['TENARAI_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: tenarai_development
  password: tenarai

  test:
  <<: *default
  database: tenarai_test
  password: tenarai

production:
  <<: *default
  database: tenarai_production
